#!/usr/bin/env python3
"""
svd_injector.py — CMSIS-SVD hardware register injector for bare-metal ARM and embedded targets.

Parses vendor CMSIS-SVD XML descriptions to map memory-mapped I/O (MMIO)
peripherals, base addresses, register bitfields, and interrupt vectors.
"""

import os
import sys
import json
import xml.etree.ElementTree as ET

def parse_int(val_str):
    """Parses hex or decimal integer string from SVD."""
    if not val_str:
        return 0
    val_str = val_str.strip()
    if val_str.lower().startswith("0x"):
        return int(val_str, 16)
    elif val_str.lower().startswith("#"):
        return int(val_str[1:], 2)
    return int(val_str)

def parse_svd(filepath):
    """Parses a CMSIS-SVD XML file and extracts peripherals and registers."""
    tree = ET.parse(filepath)
    root = tree.getroot()

    device_name = root.findtext("name", "Unknown_Device")
    device_desc = root.findtext("description", "").strip()

    peripherals = []

    for periph_elem in root.findall(".//peripheral"):
        p_name = periph_elem.findtext("name", "")
        p_desc = periph_elem.findtext("description", "").strip()
        p_base_str = periph_elem.findtext("baseAddress", "0")
        p_base = parse_int(p_base_str)

        registers = []
        for reg_elem in periph_elem.findall(".//register"):
            r_name = reg_elem.findtext("name", "")
            r_desc = reg_elem.findtext("description", "").strip()
            r_offset_str = reg_elem.findtext("addressOffset", "0")
            r_offset = parse_int(r_offset_str)
            r_size = parse_int(reg_elem.findtext("size", "32"))
            r_access = reg_elem.findtext("access", "read-write")

            abs_addr = p_base + r_offset
            registers.append({
                "name": f"{p_name}_{r_name}",
                "short_name": r_name,
                "offset": r_offset,
                "address": abs_addr,
                "address_hex": f"0x{abs_addr:08X}",
                "size_bits": r_size,
                "access": r_access,
                "description": r_desc
            })

        interrupts = []
        for int_elem in periph_elem.findall("interrupt"):
            i_name = int_elem.findtext("name", "")
            i_val = parse_int(int_elem.findtext("value", "0"))
            interrupts.append({"name": i_name, "vector": i_val})

        peripherals.append({
            "name": p_name,
            "description": p_desc,
            "base_address": p_base,
            "base_address_hex": f"0x{p_base:08X}",
            "register_count": len(registers),
            "registers": registers,
            "interrupts": interrupts
        })

    return {
        "device": device_name,
        "description": device_desc,
        "peripheral_count": len(peripherals),
        "peripherals": peripherals
    }

def print_svd_summary(data):
    print("=" * 80)
    print("  CMSIS-SVD HARDWARE PERIPHERAL & REGISTER MAP")
    print("=" * 80)
    print(f"  Device Name: {data['device']}")
    if data['description']:
        print(f"  Description: {data['description']}")
    print(f"  Peripherals Defined: {data['peripheral_count']}")
    print()

    print(f"  {'Peripheral':<16} {'Base Address':<14} {'Registers':<12} {'Interrupts':<14} {'Description'}")
    print("  " + "-" * 76)
    for p in data["peripherals"]:
        int_str = ", ".join(f"{i['name']}(#{i['vector']})" for i in p["interrupts"]) if p["interrupts"] else "none"
        desc = p["description"][:28] + "..." if len(p["description"]) > 28 else p["description"]
        print(f"  {p['name']:<16} {p['base_address_hex']:<14} {p['register_count']:<12} {int_str:<14} {desc}")
    print("=" * 80)

def generate_ghidra_python_script(svd_data, out_path):
    """Generates a Ghidra Python pre-script to inject symbols and memory blocks."""
    lines = [
        "# Auto-generated by ghidra-report svd_injector.py",
        f"# Device: {svd_data['device']}",
        "from ghidra.program.model.symbol import SourceType",
        "from ghidra.program.model.address import AddressSpace",
        "",
        "mem = currentProgram.getMemory()",
        "symTable = currentProgram.getSymbolTable()",
        "space = currentProgram.getAddressFactory().getDefaultAddressSpace()",
        ""
    ]

    for p in svd_data["peripherals"]:
        p_name = p["name"]
        base = p["base_address"]
        lines.append(f"# Peripheral: {p_name} @ 0x{base:08X}")
        lines.append(f"baseAddr = space.getAddress(0x{base:08X})")
        lines.append(f"try:")
        lines.append(f"    if not mem.contains(baseAddr):")
        lines.append(f"        mem.createUninitializedBlock('{p_name}', baseAddr, 0x1000, False)")
        lines.append(f"except Exception as e:")
        lines.append(f"    pass")
        lines.append("")

        for r in p["registers"][:20]: # Limit to main registers per block
            addr = r["address"]
            sym = r["name"]
            lines.append(f"try:")
            lines.append(f"    regAddr = space.getAddress(0x{addr:08X})")
            lines.append(f"    symTable.createLabel(regAddr, '{sym}', SourceType.USER_DEFINED)")
            lines.append(f"except Exception:")
            lines.append(f"    pass")
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[+] Generated Ghidra SVD injection pre-script: {out_path}")

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <inspect|json|generate-ghidra-script> <file.svd> [out_file]")
        sys.exit(1)

    action = sys.argv[1].lower()
    svd_file = sys.argv[2]

    if not os.path.isfile(svd_file):
        print(f"Error: SVD file not found: {svd_file}", file=sys.stderr)
        sys.exit(1)

    data = parse_svd(svd_file)

    if action == "inspect":
        print_svd_summary(data)
    elif action == "json":
        out_file = sys.argv[3] if len(sys.argv) > 3 else None
        if out_file:
            with open(out_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
            print(f"[+] Exported SVD JSON to: {out_file}")
        else:
            print(json.dumps(data, indent=2))
    elif action == "generate-ghidra-script":
        out_file = sys.argv[3] if len(sys.argv) > 3 else "inject_svd_symbols.py"
        generate_ghidra_python_script(data, out_file)
    else:
        print(f"Unknown action: {action}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
